/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LevelState = IDL.Nat;

export const idlService = IDL.Service({
  'getUnlockedLevels' : IDL.Func([], [LevelState], ['query']),
  'unlockNextLevel' : IDL.Func([LevelState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LevelState = IDL.Nat;
  
  return IDL.Service({
    'getUnlockedLevels' : IDL.Func([], [LevelState], ['query']),
    'unlockNextLevel' : IDL.Func([LevelState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };